compiler:
  solc:
    version: 0.8.14
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts-upgradeable@4.6.0/contracts"
dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.6.0
